// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<API_KEY>',
    appId: '1:522332906905:web:9606d4ea61127831449f08',
    messagingSenderId: '522332906905',
    projectId: 'metronome-app-f8d87',
    authDomain: 'metronome-app-f8d87.firebaseapp.com',
    storageBucket: 'metronome-app-f8d87.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<API_KEY>',
    appId: '1:522332906905:android:082b57050d4ef7d7449f08',
    messagingSenderId: '522332906905',
    projectId: 'metronome-app-f8d87',
    storageBucket: 'metronome-app-f8d87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<API_KEY>',
    appId: '1:522332906905:ios:0a62658e28293404449f08',
    messagingSenderId: '522332906905',
    projectId: 'metronome-app-f8d87',
    storageBucket: 'metronome-app-f8d87.appspot.com',
    iosBundleId: 'com.example.metronomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '<API_KEY>',
    appId: '1:522332906905:ios:986612e9f7f39926449f08',
    messagingSenderId: '522332906905',
    projectId: 'metronome-app-f8d87',
    storageBucket: 'metronome-app-f8d87.appspot.com',
    iosBundleId: 'com.example.metronomeApp.RunnerTests',
  );
}
